Repository beat-saber-modding-group/BeatSaberModInstaller, pull requests merged in 2019-04, with the labels that each got.

#8 Fix wrong file being downloaded for scoresaber
  BeatSaberModManager/Core/RemoteLogic.cs
Labels: bugfix

#14 Add material skin back in (and remove dependencies fix)
  BeatSaberModManager/BeatSaberModManager.csproj
  BeatSaberModManager/Core/PathLogic.cs
  BeatSaberModManager/Forms/FormDetailViewer.Designer.cs
  BeatSaberModManager/Forms/FormDetailViewer.cs
  BeatSaberModManager/Forms/FormDetailViewer.resx
  BeatSaberModManager/Forms/FormMain.Designer.cs
  BeatSaberModManager/Forms/FormMain.cs
  BeatSaberModManager/Forms/FormMain.resx
  BeatSaberModManager/Forms/FormPlatformSelect.Designer.cs
  BeatSaberModManager/Forms/FormPlatformSelect.cs
  BeatSaberModManager/Forms/FormPlatformSelect.resx
  BeatSaberModManager/Properties/Settings.Designer.cs
  BeatSaberModManager/Properties/Settings.settings
  BeatSaberModManager/app.config
  BeatSaberModManager/icon.ico
  BeatSaberModManager/packages.config
  packages/MaterialSkin.0.2.1/MaterialSkin.0.2.1.nupkg
  packages/MaterialSkin.0.2.1/lib/MaterialSkin.dll
Labels: enhancement

#18 Enhancements
  BeatSaberModManager.sln
  BeatSaberModManager/BeatSaberModManager.csproj
  BeatSaberModManager/Core/Helper.cs
  BeatSaberModManager/Core/RemoteLogic.cs
  BeatSaberModManager/DataModels/ReleaseInfo.cs
  BeatSaberModManager/Forms/FormDetailViewer.Designer.cs
  BeatSaberModManager/Forms/FormDetailViewer.cs
  BeatSaberModManager/Forms/FormDetailViewer.resx
  BeatSaberModManager/Forms/FormMain.Designer.cs
  BeatSaberModManager/Forms/FormMain.cs
  BeatSaberModManager/Forms/FormMain.resx
Labels: enhancement

#23 Save/Load selected mods
  BeatSaberModManager/Core/PathLogic.cs
  BeatSaberModManager/Forms/FormMain.cs
  BeatSaberModManager/Properties/AssemblyInfo.cs
  BeatSaberModManager/Properties/Settings.Designer.cs
  BeatSaberModManager/Properties/Settings.settings
  BeatSaberModManager/app.config
Labels: enhancement

#27 Build using Constura add-on for Fody to combine assemblies
  .gitignore
  BeatSaberModManager/BeatSaberModManager.csproj
  BeatSaberModManager/FodyWeavers.xml
  BeatSaberModManager/FodyWeavers.xsd
  BeatSaberModManager/packages.config
Labels: bugfix, enhancement

#29 Save install path
  BeatSaberModManager/Core/PathLogic.cs
  BeatSaberModManager/Forms/FormMain.cs
  BeatSaberModManager/Properties/Settings.Designer.cs
  BeatSaberModManager/Properties/Settings.settings
  BeatSaberModManager/app.config
Labels: enhancement

#44 A few extra debugging buttons
  BeatSaberModManager/BeatSaberModManager.csproj
  BeatSaberModManager/Forms/FormMain.Designer.cs
  BeatSaberModManager/Forms/FormMain.cs
Labels: enhancement

#46 Fix for ScoreSaber not appearing in mods list
  BeatSaberModManager/Core/PathLogic.cs
  BeatSaberModManager/Core/RemoteLogic.cs
  BeatSaberModManager/Forms/FormMain.Designer.cs
  BeatSaberModManager/Forms/FormMain.cs
  BeatSaberModManager/Properties/AssemblyInfo.cs
  BeatSaberModManager/Properties/Settings.Designer.cs
  BeatSaberModManager/Properties/Settings.settings
  BeatSaberModManager/app.config
Labels: bugfix
